### ISSUE TITLE
A more complex test

### ISSUE THREAD

**Issue by Permagate** [JonathanSudibya/fished#1]
Fine work boss @JonathanSudibya. Looking at the test, I think testing a more complex rule might illustrate the engine's capability even better. For example, a common scenario is testing a rule that contains calling an API. Here is such scenario:

```
{
    "input": ["pokemon_name"],
    "output": ["pokemon"],
    "rule": "getPokemon(pokemon_name)",
    "value": "???"
},
{
    "input": ["pokemon"],
    "output": ["isGoodPokemon"],
    "rule": "['dragon', 'fairy'].includes(pokemon.type)",
    "value": "true"
}
```

From the above sample, some questions arose:

1. How to call an API inside the rule?
2. How to store pokemon data fetched from the API to the output?
3. How to store pokemon data (that is probably a struct that contains a lot of attributes?
4. How to check array inclusion as seen in the second rule?
5. How to handle error that we might get from calling the API?

**Comment by JonathanSudibya** [comment]
Hey @Permagate, Thanks a lot for the feedback. I will try to answer your question here (and the rest will be an example).
> 1.How to call an API inside the rule ?

You need to implement govaluate functions and pass it to the engine. And the function will be called either in `rule` or `value`
> 2. How to store pokemon data fetched from the API to the output

You can call a function in the value. So if you don't need to "check" something, you can just pass `true` in Rules and call `getPokemon(pokemon)` in Value.

> 3. How to store pokemon data (that is probably a struct that contains a lot of attributes?
You can use `map[string]interface{}` for storing big JSON. (and if you don't exactly know the structure for it)

> 4. How to check array inclusion as seen in the second rule?
`govaluate.ExpressionFunction` received varadic parameter. So you can pass it all to the function (no need to form an array).

> 5. How to handle error that we might get from calling the API?
If there is an error, it will stored in `[]error` as one of the result calling `engine.Run()`. And if it's and error output will not be assigned and left with nil. Technically the rule will be halted and will most likely to result `nil`

**Comment by JonathanSudibya** [comment]
Hey @Permagate, example will be hosted in https://github.com/JonathanSudibya/fished-example

**Comment by JonathanSudibya** [comment]
Let's close this issue!
